version: '2'

services:
  app:
    image: 'interview-planning:latest'
    build:
      context: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    network_mode: bridge
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/calendar
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    expose:
      - 8080
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    network_mode: bridge
    container_name: db
    volumes:
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
#      - interview_planning_postgres_data:/var/lib/postgresql #uncomment if need persist data from start to another start
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calendar
    expose:
      - 5432
    restart: unless-stopped
volumes:
  interview_planning_postgres_data: