version: '2'

services:
  app:
    image: 'interview-planning:latest'
    build:
      context: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    network_mode: bridge
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${PG_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${PG_USER}
      - SPRING_DATASOURCE_PASSWORD=${PG_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TOKEN_EXPIRATION_TIME=${TOKEN_EXPIRATION_TIME}

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    network_mode: bridge
    container_name: db
    volumes:
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #      - interview_planning_postgres_data:/var/lib/postgresql #uncomment if need persist data from start to another start
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
volumes:
  interview_planning_postgres_data: